# Generated by Django 3.1.4 on 2021-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_storedrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedrequests',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='timestamp'),
        ),
    ]
