# Generated by Django 3.1.4 on 2021-01-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210108_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoredRequests',
            new_name='StoredRequest',
        ),
    ]
