# Generated by Django 3.1.5 on 2021-01-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_quotes_quotesauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesauthor',
            name='author',
            field=models.CharField(max_length=100, unique=True, verbose_name='author'),
        ),
    ]
