# Generated by Django 3.1.5 on 2021-01-27 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_auto_20210126_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesauthor',
            name='born_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='born date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotesauthor',
            name='born_in',
            field=models.CharField(default=1231, max_length=2500, verbose_name='born in'),
            preserve_default=False,
        ),
    ]
