# Generated by Django 3.1.5 on 2021-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_auto_20210127_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesauthor',
            name='born_date',
        ),
        migrations.AddField(
            model_name='quotesauthor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
