# Generated by Django 3.1.5 on 2021-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_auto_20210127_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesauthor',
            name='date_of_birth',
            field=models.CharField(max_length=100, unique=True, verbose_name='author'),
        ),
    ]
