# Generated by Django 3.1.5 on 2021-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20210127_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesauthor',
            name='description',
            field=models.CharField(default=1, max_length=6000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotesauthor',
            name='born_in',
            field=models.CharField(max_length=100, verbose_name='born in'),
        ),
    ]
